# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib trlasso
#' @importFrom Rcpp sourceCpp evalCpp
NULL

#' calculate covariance matrix
#'
#' @param X design matrix
#' @return covariance matrix
#' @keywords internal
#'
covC <- function(X) {
    .Call('_trlasso_covC', PACKAGE = 'trlasso', X)
}

#' soft thresholding function for transfer lasso
#'
#' @param z z
#' @param g1 gamma1
#' @param g2 gamma2
#' @param b b
#' @return value
#' @keywords internal
#'
softThresholdC2 <- function(z, g1, g2, b) {
    .Call('_trlasso_softThresholdC2', PACKAGE = 'trlasso', z, g1, g2, b)
}

#' Optimize a linear regression model by coordinate descent algorithm using a covariance matrix
#'
#' @param Gamma covariance matrix of explanatory variables
#' @param gamma covariance vector of explanatory and objective variables
#' @param lambda lambda sequence
#' @param alpha alpha
#' @param init_beta initial values of beta
#' @param beta_tilde initial estimates (source parameters) of beta
#' @param maxit max iteration
#' @param eps convergence threshold for optimization
#' @param strong whether use strong screening or not
#' @return standardized beta
#' @keywords internal
#' @export
covCdaC <- function(Gamma_, gamma_, lambda_, init_beta, beta_tilde_, penalty_factor_lasso_, penalty_factor_trlasso_, alpha = 1, maxit = 1e+4, eps = 1e-04, strong = TRUE) {
    .Call('_trlasso_covCdaC', PACKAGE = 'trlasso', Gamma_, gamma_, lambda_, init_beta, beta_tilde_, penalty_factor_lasso_, penalty_factor_trlasso_, alpha, maxit, eps, strong)
}

